name: Backend Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Service containers to run with the job
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eos_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Create test database and run migrations
      working-directory: ./backend
      env:
        TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eos_test
      run: |
        # Create UUID extension if it doesn't exist
        PGPASSWORD=postgres psql -h localhost -U postgres -d eos_test -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
        
        # Run the test schema setup
        PGPASSWORD=postgres psql -h localhost -U postgres -d eos_test -f src/tests/setup-test-schema.sql

    - name: Run tests
      working-directory: ./backend
      env:
        NODE_ENV: test
        TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eos_test
        JWT_SECRET: test-jwt-secret-github-actions
        JWT_REFRESH_SECRET: test-refresh-secret-github-actions
        JWT_EXPIRES_IN: 15m
        JWT_REFRESH_EXPIRES_IN: 7d
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_TEST_KEY }}
        STRIPE_WEBHOOK_SECRET: whsec_test_secret_for_github_actions
        OPENAI_API_KEY: sk-fake-key-for-testing-only
        # Microsoft OAuth (fake values for testing)
        MICROSOFT_CLIENT_ID: fake-microsoft-client-id
        MICROSOFT_CLIENT_SECRET: fake-microsoft-secret
        MICROSOFT_TENANT_ID: fake-tenant-id
        MICROSOFT_CALLBACK_URL: http://localhost:3001/api/v1/oauth/microsoft/callback
        # Google OAuth (fake values for testing)
        GOOGLE_CLIENT_ID: fake-google-client-id
        GOOGLE_CLIENT_SECRET: fake-google-secret
        GOOGLE_CALLBACK_URL: http://localhost:3001/api/v1/oauth/google/callback
        # Email settings (fake values for testing)
        SENDGRID_API_KEY: fake-sendgrid-key
        SENDGRID_FROM_EMAIL: test@test.com
        EMAIL_SERVICE: smtp
        EMAIL_FROM: test@test.com
        SMTP_HOST: localhost
        SMTP_PORT: 1025
        SMTP_USER: test
        SMTP_PASS: test
        # Frontend URL
        FRONTEND_URL: http://localhost:5173
      run: |
        npm test
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: backend/coverage/
        retention-days: 30